name: tox

on:
  create:  # is used for publishing to PyPI and TestPyPI
    tags:  # any tag regardless of its name, no branches
      - "**"
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "master"
  pull_request:
  release:
    types:
      - published  # It seems that you can publish directly without creating
      - prereleased
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

env:
  packages: sword-devel python3-tox git gcc-c++ python3-devel

jobs:

  packaging:
    runs-on: ubuntu-20.04
    container: fedora:latest
    steps:
      - name: Install DNF packages
        run: sudo dnf install -y ${{ env.packages }}
      - uses: actions/checkout@v2
      - name: Run tox
        run: tox -e packaging

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    container:  fedora:latest  # runs inside of this image, remove this to run on host
    steps:
      - name: install dnf tools
        run: sudo dnf install -y ${{ env.packages }}
      - uses: actions/checkout@v2
      - name: run test
        run: tox -e py$(printf "${{ matrix.python }}" | tr -d '.')

  publish:
    needs:
      - packaging
      - test
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    env:
      PY_COLORS: 1
      TOXENV: packaging
    container: fedora:latest
    steps:
      - name: Install DNF tools
        run: sudo dnf install -y ${{ env.packages }}
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build dists
        run: python setup.py sdist
      - name: Publish to pypi.org
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
